//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selection.Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public Courses()
        {
            this.TakenCourse = new HashSet<TakenCourse>();
        }
    
        public int CourseId { get; set; }
        public Nullable<int> FieldId { get; set; }
        public string Name { get; set; }
        public string Professor { get; set; }
        public string Time { get; set; }
    
        public virtual Courses Courses1 { get; set; }
        public virtual Courses Courses2 { get; set; }
        public virtual ICollection<TakenCourse> TakenCourse { get; set; }
    }
}
