//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selection.Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakenCourse
    {
        public int ID { get; set; }
        public int CoureseId { get; set; }
        public int TakenCourseId { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Students Students { get; set; }
    }
}
